#Server Port
server.port=8090

#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Connect With Mongo db
spring.mongodb.uri=mongodb://localhost:27017/aifitnessrecommendation
spring.mongodb.database=fitnessrecommendation


#Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
#Store Msg In Kafka In Key Value Pair
spring.kafka.consumer.group-id=activity-proceser-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#We dont need Header
spring.kafka.consumer.properties.spring.json.use.type.headers=false

#Type Of Class : mean which data is come from kafka that map into the activity class
spring.kafka.consumer.properties.spring.json.value.default.type=com.fitness.aiservices.model.Activity
#All(* mean all) Packages Are Trusted
spring.kafka.consumer.properties.spring.json.trusted.packages="*"

#Topic
app.kafka.topic.name=activity-event

#Ai Model Configure
spring.ai.openai.api-key=${OPEN_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=google/gemma-4-26b-a4b-it
