spring.application.name=api-gateway

server.port=8080
eureka.client.server-url.defaultZone=http://localhost:8761/eureka/

# Enable discovery (if using Eureka)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#User Services 
spring.cloud.gateway.routes[0].id=USER-SERVICES
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICES
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

#Activity Services 
spring.cloud.gateway.routes[1].id=ACTIVITY-SERVICES
spring.cloud.gateway.routes[1].uri=lb://ACTIVITY-SERVICES
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activity/**

#Ai Services 
spring.cloud.gateway.routes[2].id=AI-SERVICES
spring.cloud.gateway.routes[2].uri=lb://AI-SERVICES
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recommendations/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG