spring.application.name=api-gateway
server.port=8080

# # Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# # Enable discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# USER SERVICE
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICES
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**

# # ACTIVITY SERVICE
# # spring.cloud.gateway.routes[1].id=activity-service
# # spring.cloud.gateway.routes[1].uri=http://localhost:8085
# # spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activity/**

# # AI SERVICE (adjust if needed)
# spring.cloud.gateway.routes[2].id=ai-service
# spring.cloud.gateway.routes[2].uri=http://localhost:8090
# spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recommendations/**