spring.application.name=api-gateway

server.port=8080
eureka.client.server-url.defaultZone=http://localhost:8761/eureka/

#User Services 
spring.cloud.gateway.routes[0].id=user-server
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICES
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

#Activity Services 
spring.cloud.gateway.routes[1].id=activity-server
spring.cloud.gateway.routes[1].uri=lb://ACTIVITY-SERVICES
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activity/**

#Ai Services 
spring.cloud.gateway.routes[3].id=ai-server
spring.cloud.gateway.routes[3].uri=lb://AI-SERVICES
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/recommendations/**